unit10/config/routes.rb
Rails.application.routes.draw do
  resources :selected_pets

  resources :carts

  get 'shelter/index'

  post 'shelter/adopt'
  post 'shelter/finish'

  resources :pets

  root 'shelter#index'

end

unit10/app/models/pet.rb
class Pet < ActiveRecord::Base
  has_many :selected_pets
  before_destroy :ensure_not_selected
  enum pet_type: [ :dog, :cat ]
  STATUS_TYPES = %w(Available Adopted Selected)
  validates :name, presence: true
  validates :description, presence: true, length: { in: 10..40 }
  validates :picture, allow_blank: true, format: {
      with: %r{\.(gif|jpg|png)\Z}i,
      message: 'format must be GIF, JPG or PNG'
  }

  def is_selected
    self.update(pet_status: 'Selected')
  end

  def make_available
    self.update(pet_status: 'Available')
  end

  def make_adopted
    self.update(pet_status: 'Adopted')
  end

  def is_adopted?
    pet_status == 'Adopted'
  end

  def Pet.get_available_pets
    Pet.order(:pet_type).where(pet_status: 'Available')
  end

  private

  def ensure_not_selected
    if selected_pets.empty?
      true
    else
      errors.add(:base, 'Pet has already been selected')
      false
    end
  end
end

unit10/app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :age, :description, :pet_type, :picture)
    end
end

unit10/app/helpers/pets_helper.rb
module PetsHelper
end

unit10/app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
    <% if @pet.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

          <ul>
            <% @pet.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :pet_type %><br>
      <%= f.select :pet_type, Pet.pet_types.keys.to_a %>
    </div>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :age %><br>
      <%= f.text_field :age %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description, :size => 40  %>
    </div>
    <div class="field">
      <%= f.label :picture %><br>
      <%= f.text_field :picture, :size => 40  %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

unit10/app/views/pets/_pet.html.erb
<tr class=" <%= cycle('list_line_odd' , 'list_line_even' ) %>" >

  <td><%= pet.pet_type %></td>
  <td><%= pet.name %></td>
  <td><%= pet.age %></td>
  <td><%= pet.description %></td>
  <td><%= image_tag(pet.picture, class: 'pet_image') %></td>
  <% unless @adopting %>
      <td><%= button_to 'Select Pet', selected_pets_path(pet_id: pet), remote: true %></td>
  <% end %>
</tr>

unit10/app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

unit10/app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pets</h1>

<table id="pet_list">
  <thead>
    <tr>
      <th>Pet Type</th>
      <th>Name</th>
      <th>Age</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr class=" <%= cycle('list_line_odd' , 'list_line_even' ) %>" >
      <td><%= pet.pet_type %></td>
        <td><%= pet.name %></td>
        <td><%= pet.age %></td>
        <td><%= pet.description %></td>
        <td><%= image_tag(pet.picture, class: 'pet_image') %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

unit10/app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

unit10/app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pet Type:</strong>
  <%= @pet.pet_type %>
</p>
<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pet.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@pet.picture, class: 'pet_image') %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>