unit10/config/routes.rb
Rails.application.routes.draw do
  resources :selected_pets

  resources :carts

  get 'shelter/index'

  post 'shelter/adopt'
  post 'shelter/finish'

  resources :pets

  root 'shelter#index'

end

unit10/app/models/selected_pet.rb
class SelectedPet < ActiveRecord::Base
  belongs_to :pet
  belongs_to :cart
  after_save :make_pet_unavailable
  before_destroy :make_pet_available

  private
  def make_pet_unavailable
    pet = Pet.find(pet_id)
    pet.is_selected
  end

  def make_pet_available
    pet = Pet.find(pet_id)
    pet.make_available unless pet.is_adopted?
  end
end

unit10/app/controllers/selected_pets_controller.rb
class SelectedPetsController < ApplicationController
  include CurrentCart
  before_action :set_current_cart, only: [:create]
  before_action :set_selected_pet, only: [:show, :edit, :update, :destroy]

  # GET /selected_pets
  # GET /selected_pets.json
  def index
    @selected_pets = SelectedPet.all
  end

  # GET /selected_pets/1
  # GET /selected_pets/1.json
  def show
  end

  # GET /selected_pets/new
  def new
    @selected_pet = SelectedPet.new
  end

  # GET /selected_pets/1/edit
  def edit
  end

  # POST /selected_pets
  # POST /selected_pets.json
  def create
    pet = Pet.find(params[:pet_id])
    @selected_pet = @cart.selected_pets.build(pet: pet)

    respond_to do |format|
      if @selected_pet.save
        @pets = Pet.get_available_pets
        format.html { redirect_to shelter_index_url }
        format.js {}
        format.json { render :show, status: :created, location: @selected_pet }
      else
        format.html { render :new }
        format.json { render json: @selected_pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /selected_pets/1
  # PATCH/PUT /selected_pets/1.json
  def update
    respond_to do |format|
      if @selected_pet.update(selected_pet_params)
        format.html { redirect_to @selected_pet, notice: 'Selected pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @selected_pet }
      else
        format.html { render :edit }
        format.json { render json: @selected_pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /selected_pets/1
  # DELETE /selected_pets/1.json
  def destroy
    @selected_pet.destroy
     respond_to do |format|
      format.html { redirect_to shelter_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_selected_pet
      @selected_pet = SelectedPet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def selected_pet_params
      params.require(:selected_pet).permit(:pet_id)
    end
end

unit10/app/helpers/selected_pets_helper.rb
module SelectedPetsHelper
end

unit10/app/views/selected_pets/_form.html.erb
<%= form_for(@selected_pet) do |f| %>
  <% if @selected_pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@selected_pet.errors.count, "error") %> prohibited this selected_pet from being saved:</h2>

      <ul>
      <% @selected_pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pet_id %><br>
    <%= f.text_field :pet_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

unit10/app/views/selected_pets/_selected_pet.erb
<% if selected_pet == @current_pet %>
    <tr id="current_item">
<% else %>
    <tr>
<% end %>
  <td><%= selected_pet.pet.name %></td>
  <td><%= button_to 'Remove', selected_pet, method: :delete %></td>
</tr>

unit10/app/views/selected_pets/edit.html.erb
<h1>Editing Selected Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @selected_pet %> |
<%= link_to 'Back', selected_pets_path %>

unit10/app/views/selected_pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Selected Pets</h1>

<table>
  <thead>
    <tr>
      <th>Pet</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @selected_pets.each do |selected_pet| %>
      <tr>
        <td><%= selected_pet.pet %></td>
        <td><%= selected_pet.cart %></td>
        <td><%= link_to 'Show', selected_pet %></td>
        <td><%= link_to 'Edit', edit_selected_pet_path(selected_pet) %></td>
        <td><%= link_to 'Destroy', selected_pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Selected pet', new_selected_pet_path %>

unit10/app/views/selected_pets/new.html.erb
<h1>New Selected Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', selected_pets_path %>

unit10/app/views/selected_pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pet:</strong>
  <%= @selected_pet.pet %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @selected_pet.cart %>
</p>

<%= link_to 'Edit', edit_selected_pet_path(@selected_pet) %> |
<%= link_to 'Back', selected_pets_path %>